moka:
  is-server-worker: true

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 9uGp@iRB8g3VsQU
    listener:
      simple:
        acknowledge-mode: MANUAL
#      direct:
#        acknowledge-mode: MANUAL
